### PR TITLE
@Positive and @Max

### PR DESCRIPTION
**Pull request by magx2**
I found out that you do not support `@Positive` and `@Max` annotations at the same time. I know that `@Positive` could be changed to `@Min(1)`, but it's definitely is not the idiomatic way.

### CODE REVIEW

**Comment by benas** [comment]
Unfortunately it is not possible to "combine" two (or more) randomizers for a single field (in the end, a single randomizer will be selected to randomize each field). This is a known limitation documented [here](https://github.com/j-easy/easy-random/wiki/known-limitations#bean-validation).

**Comment by magx2** [comment]
So maybe you need to change architecture? When user of your library use those 2 annotations he expects some behaviour. Justifying bugs with _we can't fix it_ it's poor way to resolve it.

**Comment by benas** [comment]
Saying "Currently it is not possible to do X.. This is a known limitation documented here" is not justifying a bug. It is acknowledging a known issue.

If you look at [Java's know issues](https://www.oracle.com/technetwork/java/javase/8-known-issues-2157115.html), you can see for example:

> Currently it is not possible to programmatically invoke default interface methods using the JDI API. 

If you programmatically invoke default interface methods using the JDI API and it would not work as you expect, do you think Oracle folks are poorly justifying a bug with that statement?

Combining randomizers is not a bug, it is a feature that has been requested in #285. I did my best to come up with a clean solution but I could not find one. If you have an idea of how to do it, you are welcome to suggest it, I am always open to any improvement.

**Comment by magx2** [comment]
Maybe add handling of `@Max` annotation to `PositiveAnnotationHandler`?

**Comment by benas** [comment]
That would lead to code tangling between annotation handlers. If we follow this approach, we would also need to handle `@Min` in `NegativeAnnotationHandler` and all other combinations which is obviously not the way to go.

I should mention that Easy Random provides several way to cover your use case:

1. You can use a custom `RandomizerRegistry` where you implement the combinations you need by leveraging existing randomizers
2. You can use a custom a `RandomizerProvider` which is the main entry point for providing randomizers (this is more powerful than `RandomizerRegistry` as it give you access to the randomization context).
3. You can also register a custom randomizer for your field. This is the simplest solution IMO. Here is an example:

```java
Predicate<Field> positiveWithMaxFieldPredicate =
        FieldPredicates.isAnnotatedWith(Positive.class)
                .and(FieldPredicates.isAnnotatedWith(Max.class));
EasyRandomParameters parameters = new EasyRandomParameters()
   .randomize(positiveWithMaxFieldPredicate, new MyRandomizer());

EasyRandom easyRandom = new EasyRandom(parameters);
```

**Pull request closed without merging**
