### PR TITLE
RegularExpressionRandomizer: Remove leading and tailing boundary matc…

### PR DESCRIPTION
**Pull request by PascalSchumacher**
…hers (#315)

Not sure this is correct.

### CODE REVIEW

**Comment by benas** [comment]
Hello @PascalSchumacher 

Thanks for the PR! This is how I intended to fix the problem too. However, in hindsight, should this issue be raised against faker? Faker does in turn rely on [Generex](https://github.com/mifmif/Generex) which has the issue:

```java
Generex generex = new Generex("^[A-Fa-f0-9]*$");

// Generate random String
String randomStr = generex.random();
System.out.println(randomStr);
```

This generates `^$` which is obviously not correct. Shall we raise the issue against Generex then? I'm not sure the project is maintained anymore..

Br,
Mahmoud

**Comment by benas** [comment]
Yes, I will do it and see how it goes.

> Not sure this is correct.

I think it's fine as long as we support other boundary matchers as per the Javadoc of `java.util.regex.Pattern`:

```
                            Boundary matchers

^The beginning of a line
$ The end of a line
\b A word boundary
\B A non-word boundary
\A The beginning of the input
\G The end of the previous match
\Z The end of the input but for the final terminator, if any
\z The end of the input
```

This would work with a small change in your PR because those characters should appear at the beginning and the end of the regular expression. However, I'm thinking to *not* fix the issue in RB because we might need to support greedy and reluctant quantifiers which can appear in the middle of the regular expression. This would add a maintenance effort on our side while it should be on the dependency side.  Do you see the point?

And this is why I don't like dependencies!

**Comment by benas** [comment]
Looks like the issue was already reported: https://github.com/mifmif/Generex/issues/41 and rejected ..

**Comment by PascalSchumacher** [comment]
I would not remove more boundary matchers. One could argue for `\A`, `\z` but I would wait until this is requested to keep things simple.

As Generex will not fix this imho this should be done in random beans, but I'm o.k. if you decide otherwise.

**Pull request merged**
