### PR TITLE
Add option to disable object pool cache #449

### PR DESCRIPTION
**Pull request by JohannesBe**
```
[INFO] Reactor Summary for Easy Random 5.0.1-SNAPSHOT:
[INFO] 
[INFO] Easy Random ........................................ SUCCESS [  0.590 s]
[INFO] Easy Random Core ................................... SUCCESS [ 25.148 s]
[INFO] Easy Random Randomizers ............................ SUCCESS [  3.562 s]
[INFO] Easy Random Bean Validation ........................ SUCCESS [  4.638 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.109 s
[INFO] Finished at: 2020-12-20T15:16:01+01:00
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by JohannesBe** [comment]
As mentioned in #449 I do not exactly know what the implications of this MR could be for recursive objects (StackOverflows?). Would be great if you could shine a light on that @benas :)

**Comment by ldmi3i** [comment]
I think you can add test like this to test if recursion happens or not.

```
    @Test
    void recursionTest() {
        EasyRandomParameters par = new EasyRandomParameters();
        par.objectPoolSize(0);
        EasyRandom easyRandom = new EasyRandom(par);
        easyRandom.nextObject(A.class);
    }

    private static class A {
        private B b;

        public B getB() {
            return b;
        }

        public void setB(B b) {
            this.b = b;
        }
    }

    private static class B {
        private A a;

        public A getA() {
            return a;
        }

        public void setA(A a) {
            this.a = a;
        }
    }
```

**Comment by mjureczko** [comment]
I believe that it solves the issue correctly, but it will do no harm to add the test case suggested by @ldmi3i

**Comment by JohannesBe** [comment]
I will add the test later tonight, or later this week.

**Comment by JohannesBe** [comment]
I have added this test. This test in fact did result in a `StackOverFlowException` if the randomizationDepth was large (e.g. initial value `Integer.MAX_VALUE`). Therefore I have added a check that verifies the randomizationDepth is set when disabling the cache.

If this PR is merged, I propose we also edit the [wiki](https://github.com/j-easy/easy-random/wiki/Randomization-parameters) to document the changes in the configuration.

**Comment by JohannesBe** [comment]
I am not entirely happy with this inter-dependency of configuration parameters however, users might still set their configuration in a broken state and the consequence might not be apparent to the user at all. Any recommendations?

**Comment by mjureczko** [comment]
I'm not convinced that the large randomizationDepth issue is in fact issue. I do not expect anything but `StackOverFlowException` when using `Integer.MAX_VALUE`. Besides the relation between cache size (objectPoolSize) and randomizationDepth was always there as the cache usages do not respect randomizationDepth.

**Comment by benas** [comment]
@JohannesBe I really appreciate the effort you've put into this, but as explained in #449 , I see no need to change the code since there is already a way to disable caching. I always recommend discussing with project maintainers about opening a PR for a feature request before actually starting the work.

Thanks again for your time and effort.

**Pull request closed without merging**
