### PR TITLE
#425 Support type variables

### PR DESCRIPTION
**Pull request by ollik1**
See https://github.com/j-easy/easy-random/issues/425

Pass the actual type along with a field that will be used to pick
correct randomizer. Consider the following example:
```
abstract class Base<T> {
	T t;
}
class Concrete extends Base<String> {}
```
If we only rely on `Field.getType()`, property `Concrete.t` would be
randomized as `Object` and then cause a runtime exception when used.

Java reflection API provides a way to get the actual type, in this case
`String`. This information is passed in `GenericField` so that the
correct randomizer can be picked later.

### CODE REVIEW

**Comment by benas** [comment]
Thank you for opening this PR. The following tests fail with `java.lang.ClassCastException: java.lang.Object cannot be cast to java.util.List`:

```java
@Test
void genericBaseClassWithList() {
    class Concrete extends GenericBaseClass<List<String>> {
        private final String y;

        public Concrete(List<String> x, String y) {
            super(x);
            this.y = y;
        }

        public String getY() {
            return y;
        }
    }

    Concrete concrete = easyRandom.nextObject(Concrete.class);
    assertThat(concrete.getX()).isInstanceOf(List.class);
    concrete.getX().forEach(System.out::println);
    assertThat(concrete.getY().getClass()).isEqualTo(String.class);
}

@Test
void testMultipleGenericLevels() {
    abstract class BaseClass<T> {
        protected T x;
        BaseClass(T x) {
            this.x = x;
        }
        public T getX() {
            return x;
        }
    }

    abstract class GenericBaseClass<T, P> extends BaseClass<T> {
        protected P y;
        GenericBaseClass(T x, P y) {
            super(x);
            this.y = y;
        }
        public P getY() {
            return y;
        }
    }

    class Concrete extends GenericBaseClass<String, Long> {
        Concrete(String x, Long y) {
            super(x, y);
        }
    }

    Concrete concrete = easyRandom.nextObject(Concrete.class);
    assertThat(concrete.getX()).isInstanceOf(String.class);
    assertThat(concrete.getY()).isInstanceOf(Long.class);
    System.out.println("concrete.getX() = " + concrete.getX());
    System.out.println("concrete.getY() = " + concrete.getY());
}
```

This enhancement is really tricky. We had several attempts to implement it but we came to the conclusion that there is no clean way to do it until reified generics are supported in the Java reflection API (I invite you to read the discussions in #375 , #242 and #386 ). Do you agree?

That's why we ended up documenting this in the [known limitations](https://github.com/j-easy/easy-random/wiki/known-limitations#type-erasure) section.

**Comment by seregamorph** [comment]
@benas for sure you are right regarding given samples. But this PR still enhances the situation, it may become a step forward.
I believe, the Pareto rule works here: such change will cover 80% of possible cases.
It covers all mine (because right now I need to workaround it like set up randomization of base `Serializable` (uppermost generic type in my case) type to one of subtypes.
The change looks harmless (had to resolve merge conflicts locally), all existing use cases still work fine. To play more safe, the introduced class `GenericField` may become package visible (instead of public), new utility methods should be placed in `org.jeasy.random` (not `org.jeasy.random.util`). This way you can keep space for breaking possible back compatibility (on implementation; not behavioral).

Anyway, that's just my humble opinion.

**Comment by benas** [comment]
@seregamorph Thank you for sharing your thoughts on this!

Up until now, I was reluctant to introduce a half-backed feature in the library most of the time. But based on the popularity of this feature request, I think it makes sense to add it at least for common use cases, we can always document non supported use cases in the "known limitations" section of the docs.

That said, I would not bother with the `genericBaseClassWithList` test failing with this PR as this is similar to what is already documented as unsupported (see https://github.com/j-easy/easy-random/wiki/known-limitations#composite-collections). However, `testMultipleGenericLevels` should really pass as this a very common use case.

My other concern with this PR is the introduction of this new `GenericField` concept. This abstraction is confusing to me, especially when I have to think about when I should write `field.getField().getType()` vs `field.getType()`. Moreover, this impacts almost everywhere where `Field` is used which should now be `GenericField` (including public APIs of `ReflectionUtils` which is a breaking change). Making this concept package private and moving utility methods in `org.jeasy.random` means we would have scattered utility classes (`SomeInternalUtils` besides `ReflectionUtils`) which is not the goal in the first place.

I believe we can support the suggested use cases with a simpler approach: whenever we populate a field, we could check it if it is generic and try to get the type from its base class (or one from its hierarchy). I tried to implement this in https://github.com/j-easy/easy-random/commit/0cadecef93abbdb34f535a0572b60e4efdb28cfa. This approach has a minimal impact (only `FieldPopulator`), passes all tests of this PR + the above `testMultipleGenericLevels`, and does not introduce any regression or API breaking change.

@ollik1 @seregamorph I would be grateful if you could take a look at this attempt in order to move this feature request forward and include it in the upcoming 4.3. Many thanks upfront.

**Comment by seregamorph** [comment]
@benas I will take care of if. Already have some prototypes (based on spring-core and fasterxml-classmate just for investigations). Trying to extract working prototype without new external dependencies.

**Comment by benas** [comment]
@seregamorph ok thank you! I opened #439 to make it easier to review the changes. @ollik1 your feedback is welcome as well!

**Comment by benas** [comment]
> I believe, the Pareto rule works here: such change will cover 80% of possible cases.

I agree, and this is a good start! Both this #426 and #439 cover those cases. But as explained [previously](https://github.com/j-easy/easy-random/pull/426#issuecomment-722041902), I had some concerns with this PR. So I'm closing it in favor of #439.

@ollik1 Thank you for your contribution anyway! And thanks to @seregamorph for the review and follow up!

**Pull request closed without merging**
